# Generated by Django 3.0.3 on 2020-03-07 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='self_intoro',
            new_name='introduction',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favorite_words',
        ),
    ]
