# Generated by Django 3.0.3 on 2020-03-07 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200307_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='birth_date',
            new_name='birth_day',
        ),
    ]
