# Generated by Django 3.0.3 on 2020-03-08 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200307_0043'),
        ('ans', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnsdModel',
            new_name='AnsModel',
        ),
    ]
