# Generated by Django 3.0.3 on 2020-03-08 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20200307_0043'),
        ('ans', '0002_auto_20200308_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansmodel',
            name='board_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.BoardModel'),
        ),
    ]
