# Generated by Django 3.0.3 on 2020-03-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_auto_20200312_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='count_ans',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
