# Generated by Django 3.0.3 on 2020-03-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_boardmodel_count_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
    ]
