# Generated by Django 3.0.3 on 2020-03-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20200314_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardimage',
            name='picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
