# Generated by Django 3.0.3 on 2020-03-14 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_auto_20200315_0542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardimage',
            old_name='picture',
            new_name='image',
        ),
    ]
