# Generated by Django 3.0.3 on 2020-03-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0014_auto_20200315_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
